from .contents import NHLData
from .endpoints import (
    Season,
    GameEndpointType,
    # public endpoints
	API_TEAM_ENDPOINT, 
	API_DIVISION_ENDPOINT,
	API_CONFERENCE_ENDPOINT,
	API_DRAFT_ENDPOINT,
	API_PROSPECTS_ENDPOINT,
	API_AWARDS_ENDPOINT,
	API_STANDINGS_ENDPOINT,
	API_SCHEDULE_ENDPOINT,
    # descriptions for modifiers
	describe_team_endpoint,
	describe_standings_endpoint,
	describe_schedule_endpoint,
	describe_people_stats_endpoint,
	describe_game_endpoint,
	# dynamic endpoint creation
	create_team_endpoint, 
	create_division_endpoint,
	create_conference_endpoint,
	create_draft_endpoint,
	create_prospects_endpoint,
	create_awards_endpoint,
	create_standings_endpoint,
	create_schedule_endpoint,
	create_game_endpoint,
	create_people_endpoint,
)


__all__ = [
    'NHLData',
    'Season',
    'GameEndpointType',
	'API_TEAM_ENDPOINT', 
	'API_DIVISION_ENDPOINT',
	'API_CONFERENCE_ENDPOINT',
	'API_DRAFT_ENDPOINT',
	'API_PROSPECTS_ENDPOINT',
	'API_AWARDS_ENDPOINT',
	'API_STANDINGS_ENDPOINT',
	'API_SCHEDULE_ENDPOINT',
	'describe_team_endpoint',
	'describe_standings_endpoint',
	'describe_schedule_endpoint',
	'describe_people_stats_endpoint',
	'describe_game_endpoint',
	'create_team_endpoint', 
	'create_division_endpoint',
	'create_conference_endpoint',
	'create_draft_endpoint',
	'create_prospects_endpoint',
	'create_awards_endpoint',
	'create_standings_endpoint',
	'create_schedule_endpoint',
	'create_game_endpoint',
	'create_people_endpoint',
]
