-- Author: Brent Barbachem 
-- Note: Generated using MySQL Workbench
-- Description: 
-- Simple database file for starting work on the data analytics project 
-- The main role for this database is quick lookups for all shot events.
-- MySQL Script generated by MySQL Workbench
-- Sat Nov 13 14:49:19 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ShotTracker
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ShotTracker` ;

-- -----------------------------------------------------
-- Schema ShotTracker
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ShotTracker` DEFAULT CHARACTER SET utf8 ;
USE `ShotTracker` ;

-- -----------------------------------------------------
-- Table `ShotTracker`.`GameInfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ShotTracker`.`GameInfo` ;

CREATE TABLE IF NOT EXISTS `ShotTracker`.`GameInfo` (
  `gameID` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `homeTeamID` INT NOT NULL,
  `homeTeamScore` INT NOT NULL,
  `awayTeamID` INT NOT NULL,
  `awayTeamScore` INT NOT NULL,
  PRIMARY KEY (`gameID`, `date`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShotTracker`.`Players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ShotTracker`.`Players` ;

CREATE TABLE IF NOT EXISTS `ShotTracker`.`Players` (
  `playerID` INT NOT NULL,
  `firstName` VARCHAR(100) NOT NULL,
  `lastName` VARCHAR(100) NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `positionCode` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`playerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShotTracker`.`Rosters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ShotTracker`.`Rosters` ;

CREATE TABLE IF NOT EXISTS `ShotTracker`.`Rosters` (
  `teamID` INT NOT NULL,
  `playerID` INT NOT NULL,
  `season` VARCHAR(45) NOT NULL,
  `startDate` DATETIME NOT NULL,
  `endDate` DATETIME NULL,
  PRIMARY KEY (`teamID`, `playerID`, `startDate`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShotTracker`.`ShotEvents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ShotTracker`.`ShotEvents` ;

CREATE TABLE IF NOT EXISTS `ShotTracker`.`ShotEvents` (
  `gameID` INT NOT NULL,
  `shotID` INT NOT NULL,
  `result` VARCHAR(45) NOT NULL,
  `player1ID` INT NOT NULL,
  `player2ID` INT NOT NULL,
  `x` DECIMAL(10) NOT NULL,
  `y` DECIMAL(10) NOT NULL,
  PRIMARY KEY (`gameID`, `shotID`, `player1ID`, `player2ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShotTracker`.`TeamInfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ShotTracker`.`TeamInfo` ;

CREATE TABLE IF NOT EXISTS `ShotTracker`.`TeamInfo` (
  `teamID` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `abreviation` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`teamID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
